# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: 2
# Check for updates to GitHub Actions every week
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - fmulero
      - carrodher
    assignees:
      - fmulero
      - carrodher
  - package-ecosystem: "github-actions"
    directory: "/src"
    schedule:
      interval: "daily"
    reviewers:
      - fmulero
      - carrodher
    assignees:
      - fmulero
      - carrodher