# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

# https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration
# Test project
bitnami/support-test:
  - source: workflows/
    dest: .github/workflows/
bitnami/vms:
  - source: workflows/
    dest: .github/workflows/
bitnami/vulndb:
  - source: workflows/
    dest: .github/workflows/
bitnami/readme-generator-for-helm:
  - source: workflows/
    dest: .github/workflows/
# Uncoment for migration
# bitnami/charts:
#   - source: workflows/
#     dest: .github/workflows/
# bitnami/containers:
#   - source: workflows/
#     dest: .github/workflows/
# 