# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

# https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration
bitnami/vms:
  - source: workflows/
    dest: .github/workflows/
bitnami/vulndb:
  - source: workflows/
    dest: .github/workflows/
bitnami/readme-generator-for-helm:
  - source: workflows/
    dest: .github/workflows/
bitnami/minideb:
  - source: workflows/
    dest: .github/workflows/
bitnami/chart-categories-action:
  - source: workflows/
    dest: .github/workflows/
bitnami/wait-for-port:
  - source: workflows/
    dest: .github/workflows/
bitnami/render-template:
  - source: workflows/
    dest: .github/workflows/
bitnami/ini-file:
  - source: workflows/
    dest: .github/workflows/
bitnami/gonit:
  - source: workflows/
    dest: .github/workflows/
bitnami/bndiagnostic:
  - source: workflows/
    dest: .github/workflows/
bitnami/bncert:
  - source: workflows/
    dest: .github/workflows/
bitnami/healthcheck-tools:
  - source: workflows/
    dest: .github/workflows/
bitnami/charts:
  - source: workflows/
    dest: .github/workflows/
bitnami/containers:
  - source: workflows/
    dest: .github/workflows/
bitnami/charts-syncer:
  - source: workflows/
    dest: .github/workflows/
