# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] Comments based card movements'
on:
  workflow_call:
    secrets:
      BITNAMI_SUPPORT_BOARD_TOKEN:
        required: true
# Remove all permissions by default
permissions: {}
jobs:
  comments_handler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Repo checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
        with:
          fetch-depth: 1
          repository: bitnami/support
      - name: Load .env file
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9
      - name: Add to board
        id: add-to-project
        uses: actions/add-to-project@9bfe908f2eaa7ba10340b31e314148fcfe6a2458
        with:
          # Support project
          project-url: https://github.com/orgs/bitnami/projects/4
          github-token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
      - name: Move into From Build Maintenance
        uses: EndBug/project-fields@52c2f411fd7e8982ef41656212d0f6db8de5468b
        # The comment was created by bitnami-bot in a pull_request created by bitnami-bot
        if: ${{ github.actor == 'bitnami-bot' && github.event.issue.user.login == 'bitnami-bot' && github.event.issue.pull_request != null }}
        with:
          project_url: https://github.com/orgs/bitnami/projects/4
          github_token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          operation: set
          fields: Status
          values: Build Maintenance
      - name: Move into Pending
        uses: EndBug/project-fields@52c2f411fd7e8982ef41656212d0f6db8de5468b
        if: |
          (github.actor != 'bitnami-bot' || github.event.issue.user.login != 'bitnami-bot' || github.event.issue.pull_request == null) &&
          contains(fromJson(env.BITNAMI_TEAM), github.actor) &&
          (!contains(github.event.issue.labels.*.name, 'bitnami'))
        with:
          project_url: https://github.com/orgs/bitnami/projects/4
          github_token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          operation: set
          fields: Status
          values: Pending
      - name: Move into In progress
        uses: EndBug/project-fields@52c2f411fd7e8982ef41656212d0f6db8de5468b
        if: |
          (github.actor != 'bitnami-bot' || github.event.issue.user.login != 'bitnami-bot' || github.event.issue.pull_request == null) &&
          (!contains(fromJson(env.BITNAMI_TEAM), github.actor)) &&
          contains(github.event.issue.labels.*.name, 'in-progress')
        with:
          project_url: https://github.com/orgs/bitnami/projects/4
          github_token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          operation: set
          fields: Status
          values: In progress
      - name: Move into Triage
        uses: EndBug/project-fields@52c2f411fd7e8982ef41656212d0f6db8de5468b
        if: |
          (github.actor != 'bitnami-bot' || github.event.issue.user.login != 'bitnami-bot' || github.event.issue.pull_request == null) &&
          (!contains(fromJson(env.BITNAMI_TEAM), github.actor)) &&
          (!contains(github.event.issue.labels.*.name, 'in-progress')) &&
          (!contains(github.event.issue.labels.*.name, 'bitnami'))
        with:
          project_url: https://github.com/orgs/bitnami/projects/4
          github_token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          operation: set
          fields: Status
          values: Triage
  labeling:
    name: Set labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Get item info
        id: get-item
        run: |
          # Note issue_comment event is slightly different than issues or pull_request. More info here: https://docs.github.com/en/webhooks/webhook-events-and-payloads#issue_comment
          author="${{ github.event.issue.user.login }}"
          number="${{ github.event.issue.number }}"
          type="${{ github.event.issue.pull_request != null && 'pull_request' || 'issue' }}"
          echo "author=${author}" >> $GITHUB_OUTPUT
          echo "number=${number}" >> $GITHUB_OUTPUT
          echo "type=${type}" >> $GITHUB_OUTPUT
      - name: Build Maintenance labeling
        uses: fmulero/labeler@f49bf680252fc8ac12cbebb6e0ed8ea19d0712da
        if: ${{ steps.get-item.outputs.type == 'pull_request' && steps.get-item.outputs.author == 'bitnami-bot' }}
        with:
          add-labels: review-required
          remove-labels: auto-merge
