# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

# This workflow is built to manage the triage support by using GH issues.
name: '[Support] Organize triage'
on:
  workflow_call:
    secrets:
      BITNAMI_SUPPORT_BOARD_TOKEN:
        required: true
# Remove all permissions by default
permissions: {}
jobs:
  # For any opened or reopened issue, should be sent into Triage
  send_to_board:
    name: Organize triage
    runs-on: ubuntu-latest
    # Please note that projects cards are created/moved with Bitnami Bot
    permissions:
      contents: read
    steps:
      - name: Repo checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          fetch-depth: 1
          repository: bitnami/support
      - name: Load .env file
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9
      - name: Get item info
        id: get-item
        run: |
          author="${{ github.event.issue != null && github.event.issue.user.login || github.event.pull_request.user.login }}"
          number="${{ github.event.issue != null && github.event.issue.number || github.event.pull_request.number }}"
          type="${{ github.event.issue != null && 'issue' || 'pull_request' }}"
          echo "author=${author}" >> $GITHUB_OUTPUT
          echo "number=${number}" >> $GITHUB_OUTPUT
          echo "type=${type}" >> $GITHUB_OUTPUT
      - name: Add to board
        id: add-to-project
        uses: actions/add-to-project@0609a2702eefb44781da00f8e04901d6e5cd2b92
        if: ${{steps.get-item.outputs.author != 'bitnami-bot' || steps.get-item.outputs.type != 'pull_request'}}
        with:
          # Support project
          project-url: https://github.com/orgs/bitnami/projects/4
          github-token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
      - name: Add to column
        uses: EndBug/project-fields@d1a7a045d10d3342a53de0195c14c3ae72d19272
        if: ${{steps.get-item.outputs.author != 'bitnami-bot' || steps.get-item.outputs.type != 'pull_request'}}
        with:
          project_url: https://github.com/orgs/bitnami/projects/4
          github_token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          operation: set
          fields: Status
          values: ${{ (contains(fromJson(env.BITNAMI_TEAM), steps.get-item.outputs.author)) && 'From Bitnami' || 'Triage' }}
  labeling:
    name: Set labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Repo checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          fetch-depth: 1
          repository: bitnami/support
      - name: Load .env file
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9
      - name: Get item info
        id: get-item
        env:
          GITHUB_TOKEN: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
        run: |
          author="${{ github.event.issue != null && github.event.issue.user.login || github.event.pull_request.user.login }}"
          number="${{ github.event.issue != null && github.event.issue.number || github.event.pull_request.number }}"
          type="${{ github.event.issue != null && 'issue' || 'pull_request' }}"
          repo_name="${{ github.event.repository.name }}"
          [[ "${BITNAMI_TEAM}" == *"${author}"* ]] && group="support" || group="triage"
          assignment=$(echo "$REPO_ASSIGNMENT" | jq -cr ".\"${repo_name}\" // .default")
          assignment_team=$(echo "$assignment" | jq -cr ".\"${group}-teams\" // empty")
          assignees=$(echo "$assignment" | jq -cr ".\"${group}-assignees\" // empty")
          # If there is no assignees and the team is not empty
          if [[ -n "$assignment_team" ]] && [[ -z "$assignees" ]]; then
            assignees=$(gh api "/orgs/bitnami/teams/${assignment_team}/members" |jq -cr 'sort_by(.login)|map(.login)|join(",")')
          fi
          echo "author=${author}" >> $GITHUB_OUTPUT
          echo "number=${number}" >> $GITHUB_OUTPUT
          echo "type=${type}" >> $GITHUB_OUTPUT
          echo "assignees=${assignees}" >> $GITHUB_OUTPUT
      - name: From Bitnami labeling
        uses: fmulero/labeler@f49bf680252fc8ac12cbebb6e0ed8ea19d0712da
        if: ${{ steps.get-item.outputs.type != 'issue' && steps.get-item.outputs.author == 'bitnami-bot' }}
        with:
          add-labels: 'automated, auto-merge'
      - name: Verify labeling
        uses: fmulero/labeler@f49bf680252fc8ac12cbebb6e0ed8ea19d0712da
        if: ${{ steps.get-item.outputs.type != 'issue' && contains(fromJson(env.BITNAMI_TEAM), steps.get-item.outputs.author) }}
        with:
          # Bitnami bot token is required to trigger CI workflows
          repo-token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          add-labels: verify
      - name: Triage labeling
        uses: fmulero/labeler@f49bf680252fc8ac12cbebb6e0ed8ea19d0712da
        if: |
          steps.get-item.outputs.type != 'issue' && steps.get-item.outputs.author != 'bitnami-bot' ||
          steps.get-item.outputs.type == 'issue'
        with:
          add-labels: ${{ (contains(fromJson(env.BITNAMI_TEAM), steps.get-item.outputs.author)) && 'bitnami' || 'triage' }}
          remove-labels: on-hold, in-progress, solved, ${{ (contains(fromJson(env.BITNAMI_TEAM), steps.get-item.outputs.author)) && 'triage' || 'bitnami' }}
      - name: 
        uses: pozil/auto-assign-issue@edee9537367a8fbc625d27f9e10aa8bad47b8723
        if: ${{ steps.get-item.outputs.author != 'bitnami-bot' }}
        with:
          numOfAssignee: 1
          assignees: ${{ steps.get-item.outputs.assignees }}
          # If we have repos with only one assignees we allow selfAssignment
          allowSelfAssign: ${{ steps.get-item.outputs.assignees == steps.get-item.outputs.author }}
