# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] PR review comment card movement'
on:
  workflow_call:
    inputs:
      author:
        required: true
        type: string
      actor:
        required: true
        type: string
      resource_url:
        required: true
        type: string
      labels:
        required: true
        type: string
      review_state:
        required: false
        type: string
      author_association:
        required: false
        type: string
    secrets:
      BITNAMI_SUPPORT_BOARD_TOKEN:
        required: true
# Remove all permissions by default
permissions: {}
jobs:
  comments_handler:
    runs-on: ubuntu-latest
    if: |
      inputs.author != 'bitnami-bot' &&
      (!contains(fromJson(inputs.labels), 'bitnami'))
    steps:
      - name: Repo checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 1
          repository: bitnami/support
      - name: Load .env file
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9
      - name: Move into Pending 
        uses: EndBug/project-fields@f42a6b2ae81d5f7d247f5464c6c995b441aadbc4
        if: |
          contains(fromJson(env.BITNAMI_TEAM), inputs.actor) &&
          inputs.review_state != 'approved'
        with:
          project_url: https://github.com/orgs/bitnami/projects/4
          resource_url: ${{ inputs.resource_url }}
          github_token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          operation: set
          fields: Status
          values: Pending
      - name: Move into Triage/In progress
        uses: EndBug/project-fields@f42a6b2ae81d5f7d247f5464c6c995b441aadbc4
        if: ${{ !contains(fromJson(env.BITNAMI_TEAM), inputs.actor) }}
        with:
          project_url: https://github.com/orgs/bitnami/projects/4
          resource_url: ${{ inputs.resource_url }}
          github_token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          operation: set
          fields: Status
          values: ${{ contains(fromJson(inputs.labels), 'in-progress') && 'In progress' || 'Triage' }}