# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: '[Support] PR review card movement'
on:
  workflow_call:
    secrets:
      BITNAMI_SUPPORT_BOARD_TOKEN:
        required: true
# Remove all permissions by default
permissions: {}
jobs:
  comments_handler:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login != 'bitnami-bot' &&
      (!contains(github.event.pull_request.labels.*.name, 'bitnami'))
    steps:
      - name: Add to board
        id: add-to-project
        uses: actions/add-to-project@2e5cc851ca7162e9eb510e6da6a5c64022e606a7
        with:
          # Support project
          project-url: https://github.com/orgs/bitnami/projects/4
          github-token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
      - name: Move into Pending
        uses: EndBug/project-fields@8bb6135400ca0288b7604252bf191f52969b828a
        if: ${{ github.event.review.state == 'changes_requested' }}
        with:
          project_url: https://github.com/orgs/bitnami/projects/4
          github_token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          operation: set
          fields: Status
          values: Pending
      - name: Move into In progress/Triage
        uses: EndBug/project-fields@8bb6135400ca0288b7604252bf191f52969b828a
        if: ${{ github.event.review.state == 'dismissed' }}
        with:
          project_url: https://github.com/orgs/bitnami/projects/4
          github_token: ${{ secrets.BITNAMI_SUPPORT_BOARD_TOKEN }}
          operation: set
          fields: Status
          values: ${{ contains(github.event.pull_request.labels.*.name, 'in-progress') && 'In progress' || 'Triage' }}
