# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

name: Sync Workflow Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: {}
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@8b92be3375cf1d1b0cd579af488a9255572e4619
        with:
          # This token requires workflows permissions.
          GH_PAT: ${{ secrets.BITNAMI_BOT_SUPPORT_TOKEN }}
          PR_LABELS: support
          GIT_USERNAME: bitnami-bot
          GIT_EMAIL: bitnami-bot@vmware.com
          COMMIT_BODY: "\n\nSigned-off-by: bitnami-bot <bitnami-bot@vmware.com>"
