# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

name: Sync Workflow Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: {}
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@3023dac7ce66c18b119e2012348437eadeaea116
        with:
          # This token requires workflows permissions.
          GH_PAT: ${{ secrets.BITNAMI_BOT_SUPPORT_TOKEN }}
          PR_LABELS: support
          GIT_USERNAME: bitnami-bot
          GIT_EMAIL: bitnami-bot@vmware.com
          COMMIT_BODY: "\n\nSigned-off-by: bitnami-bot <bitnami-bot@vmware.com>"
